from nemo.collections.asr.modules.ssl_modules.augmentation import MultiSpeakerNoiseAugmentation, WavLMAugmentation
from nemo.collections.asr.modules.ssl_modules.masking import ConvFeatureMaksingWrapper, RandomBlockMasking
from nemo.collections.asr.modules.ssl_modules.multi_softmax_decoder import MultiSoftmaxDecoder
from nemo.collections.asr.modules.ssl_modules.quantizers import RandomProjectionVectorQuantizer
