# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "preprocessor"
backend: "python"
max_batch_size: 32

parameters [
  {
    key: "model_name"
    value: { string_value: "nvidia/parakeet-ctc-1.1b" }  # .nemo model or pretrained model name
  }
]

input [
  {
    name: "WAV"
    data_type: TYPE_FP32
    dims: [-1]
    allow_ragged_batch: true
  }
  {
    name: "WAV_LENGTH"
    data_type: TYPE_INT32
    dims: [1]
  }
  {
    name: "sampling_rate"    # sampling rate is used for deciding whether to do upsampling and downsampling
    data_type: TYPE_INT32
    dims: [1]
  }
]


output [
  {
    name: "processed_signal"
    data_type: TYPE_FP32
    dims: [80, -1]
  }
  {
    name: "processed_signal_length"
    data_type: TYPE_INT32
    dims: [1]
  }
]

dynamic_batching {
    preferred_batch_size: [32]
    
}

instance_group [
    {
      count: 1
      kind: KIND_GPU
    }
  ]
