from nemo.collections.asr.parts.postprocessing.asr_text_postprocessor import AbstractTextPostProcessor
from nemo.collections.asr.parts.postprocessing.language_normalizations.default_normalizer import DefaultTextPostProcessor
from nemo.collections.asr.parts.postprocessing.language_normalizations.en_normalizer import EnglishTextPostProcessor
from nemo.collections.asr.parts.postprocessing.language_normalizations.de_normalizer import GermanTextPostProcessor
from nemo.collections.asr.parts.postprocessing.language_normalizations.es_normalizer import SpanishTextPostProcessor