
output_dir: ???

data:
  pattern: "*.json"
  manifest_filepath: ???
  tarred_audio_filepaths: null
  sample_rate: 16000
  max_duration: 30 # you may need to update it for your dataset
  min_duration: 0.1
  batch_duration: 300  # you may disable batch_duration by setting it to `null`
  batch_size: null 
  shuffle: false
  seed: 42
  num_workers: 8
  pin_memory: true
  quadratic_duration: 30
  num_buckets: 30
  num_cuts_for_bins_estimate: 10000
  bucket_buffer_size: 10000
  shuffle_buffer_size: 10000

  random_padding:
      prob: 1.0
      min_pad_duration: 0.0  # minimum duration of pre/post padding in seconds
      max_pad_duration: 3.0  # maximum duration of pre/post padding in seconds
      max_total_duration: 40.0  # maximum total duration of the padded audio in seconds
      pad_distribution: 'constant'  # distribution of padding duration, 'uniform' or 'normal' or 'constant'
      pre_pad_duration: 0.2
      post_pad_duration: 3.0

  augmentor:
    white_noise:
      prob: 1.0
      min_level: -80
      max_level: -40
    gain:
      prob: 0.5
      min_gain_dbfs: -10.0
      max_gain_dbfs: 10.0
    noise:
      prob: 0.99
      manifest_path: ???
      min_snr_db: 0
      max_snr_db: 20
      max_gain_db: 300.0