# Copyright (c) 2019, NVIDIA CORPORATION. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#  * Neither the name of NVIDIA CORPORATION nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

name: "feature-extractor-trt-vad-streaming"
platform: "custom"
default_model_filename: "libfeature-extractor.so"
max_batch_size: 1

sequence_batching {
  max_sequence_idle_microseconds: 60000000
  control_input [
{
      name: "START"
      control [
        {
          kind: CONTROL_SEQUENCE_START
          int32_false_true: [ 0, 1 ]
        }
      ]
    },
    {
      name: "READY"
      control [
        {
          kind: CONTROL_SEQUENCE_READY
          int32_false_true: [ 0, 1 ]
        }
      ]
    }
  ]
}


input [
{
    name: "AUDIO_SIGNAL"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "SAMPLE_RATE"
    data_type: TYPE_UINT32
    dims: [ 1 ]
  }
]

output [
  {
    name: "AUDIO_FEATURES"
    data_type: TYPE_FP32
    dims: [64, -1]
  },
  {
    name: "AUDIO_PROCESSED"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]

parameters [
  {
    key: "num_features"
    value: { string_value: "64" }
  },
  {
    key: "window_size"
    value: { string_value: "0.02" }
  },
  {
    key: "window_stride"
    value: { string_value: "0.01" }
  },
  {
    key: "dither"
    value: { string_value: "1e-05" }
  },
  {
    key: "gain"
    value: { string_value: "1" }
  },
  {
    key: "precalc_norm_params"
    value: { string_value: "False" }
  },
  {
    key: "norm_per_feature"
    value: { string_value: "True" }
  },
  {
    # Specify custom mean as single value or comma separated values
    key: "mean"
    value: { string_value: "-14.95827016, -12.71798736, -11.76067913, -10.83311182, -10.6746914, -10.15163465, -10.05378331, -9.53918999, -9.41858904, -9.23382904, -9.46470918, -9.56037, -9.57434245, -9.47498732, -9.7635205, -10.08113074, -10.05454561, -9.81112681, -9.68673603, -9.83652977, -9.90046248, -9.85404766, -9.92560366, -9.95440354, -10.17162966, -9.90102482, -9.47471025, -9.54416855, -10.07109475, -9.98249912, -9.74359465, -9.55632283, -9.23399915, -9.36487649, -9.81791084, -9.56799225, -9.70630899, -9.85148006, -9.8594418, -10.01378735, -9.98505315, -9.62016094, -10.342285, -10.41070709, -10.10687659, -10.14536695, -10.30828702, -10.23542833, -10.88546868, -11.31723646, -11.46087382, -11.54877829, -11.62400934, -11.92190509, -12.14063815, -11.65130117, -11.58308531, -12.22214663, -12.42927197, -12.58039805, -13.10098969, -13.14345864, -13.31835645, -14.47345634"  }
  },
  {
    # Specify custom stddev as single value or comma separated values
    key: "stddev"
    value: { string_value: "3.81402054, 4.12647781, 4.05007065, 3.87790987, 3.74721178, 3.68377423, 3.69344, 3.54001005, 3.59530412, 3.63752368, 3.62826417, 3.56488469, 3.53740577, 3.68313898, 3.67138151, 3.55707266, 3.54919572, 3.55721289, 3.56723346, 3.46029304, 3.44119672, 3.49030548, 3.39328435, 3.28244406, 3.28001423, 3.26744937, 3.46692348, 3.35378948, 2.96330901, 2.97663111, 3.04575148, 2.89717604, 2.95659301, 2.90181116, 2.7111687, 2.93041291, 2.86647897, 2.73473181, 2.71495654, 2.75543763, 2.79174615, 2.96076456, 2.57376336, 2.68789782, 2.90930817, 2.90412004, 2.76187531, 2.89905006, 2.65896173, 2.81032176, 2.87769857, 2.84665271, 2.80863137, 2.80707634, 2.83752184, 3.01914511, 2.92046439, 2.78461139, 2.90034605, 2.94599508, 2.99099718, 3.0167554, 3.04649716, 2.94116777" }
  },
  {
    key: "streaming"
    value: { string_value: "True" }
  },

  {
    key: "padding_factor"
    value: { string_value: "2" }
  },

  {
    key: "transpose"
    value: { string_value: "False" }
  },
  {
    key: "out_num_time_steps"
    value: { string_value: "False" }
  }

]



