# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "asr_ctc_chunked_offline"
backend: "python"
max_batch_size: 32

parameters [
  {
    key: "model_name"
    value: { string_value: "nvidia/parakeet-ctc-1.1b" }  # .nemo model or pretrained model name
  },
  {
    key: "dtype"
    value: { string_value: "float16" }
  },
  {
    key: "chunk_len_in_secs"
    value: { string_value: "20.0" }
  },
  {
    key: "total_buffer_in_secs"
    value: { string_value: "30.0" }
  },
  {
    key: "batch_size"
    value: { string_value: "32"}
  },
  {
    key: "chunk_strategy"
    value: { string_value: "hf_chunked_infer"}  # hf_chunked_infer, nemo_chunked_infer
  }
]


input [
  {
    name: "WAV"
    data_type: TYPE_FP32
    dims: [-1]
    allow_ragged_batch: true
  },
  {
    name: "WAV_LENS"
    data_type: TYPE_INT32
    dims: [1]
  }
]


output [
  {
    name: "TRANSCRIPTS"
    data_type: TYPE_STRING
    dims: [1]
  }
]

dynamic_batching {
    preferred_batch_size: [32]
    max_queue_delay_microseconds: 1000
  }

instance_group [
    {
      count: 1
      kind: KIND_GPU
    }
  ]
