HYDRA_FULL_ERROR=1 python3 main.py \
    +ci_test=True \
    training=mt5/170m \
    run_data_preparation=False \
    run_training=True \
    run_conversion=False \
    run_finetuning=False \
    run_evaluation=False \
    bignlp_path=${GIT_CLONE_PATH} \
    data_dir=/lustre/fsw/joc/big_nlp/mt5/dataset/ci_data \
    base_results_dir=${BASE_RESULTS_DIR} \
    "container='${BUILD_IMAGE_NAME_SRUN}'" \
    cluster.partition=${SLURM_PARTITION} \
    cluster.account=${SLURM_ACCOUNT} \
    cluster.gpus_per_task=null \
    cluster.gpus_per_node=null \
    cluster.job_name_prefix="${SLURM_ACCOUNT}-bignlp_ci:" \
    training.run.name=${RUN_NAME} \
    training.run.time_limit="20:00" \
    training.trainer.num_nodes=1 \
    training.trainer.max_steps=100 \
    training.trainer.log_every_n_steps=1 \
    training.trainer.val_check_interval=20 \
    training.trainer.limit_val_batches=5 \
    training.model.tensor_model_parallel_size=2 \
    training.model.pipeline_model_parallel_size=1