dataset:
  _target_: "nemo.collections.tts.torch.data_ssl_vocoder.SSLVocoderDataset"
  manifest_filepath: ${train_dataset}
  ssl_model_type: ${ssl_model_type}
  ssl_model_ckpt_path: ${ssl_model_ckpt_path}
  ssl_content_emb_type: ${ssl_content_emb_type}
  sample_rate: ${sample_rate}
  n_segments: ${train_n_segments}
  max_duration: ${train_max_duration}
  min_duration: ${train_min_duration}
dataloader_params:
  drop_last: false
  shuffle: true
  batch_size: 32
  num_workers: 4
  pin_memory: true
  