# How to use? Build it from NeMo root folder:
# 1. git clone https://github.com/NVIDIA/NeMo.git && cd NeMo
# 2. DOCKER_BUILDKIT=1 docker build -t nemo:22.12.2 -f ./scripts/installers/Dockerfile.ngramtools .

from nvcr.io/nvidia/nemo:22.12

WORKDIR /workspace/nemo

COPY scripts/installers/* /workspace/nemo/scripts/installers

RUN /bin/bash scripts/installers/install_beamsearch_decoders.sh

RUN /bin/bash scripts/installers/install_opengrm.sh
