import pprint

data = {
    'n_action_bins': 256,
    'vision_backbone_id': 'dinosiglip-vit-so-224px',
    'llm_backbone_id': 'llama2-7b-pure',
    'arch_specifier': 'no-align+fused-gelu-mlp',
    'output_projector_states': False,
    'use_fused_vision_backbone': True,
    'timm_model_ids': [
        'vit_large_patch14_reg4_dinov2.lvd142m',
        'vit_so400m_patch14_siglip_224',
    ],
    'timm_override_act_layers': [None, None],
    'image_sizes': [224, 224],
    'image_resize_strategy': 'resize-naive',
    'hf_llm_id': 'meta-llama/Llama-2-7b-hf',
    'llm_max_length': 2048,
    'pad_token_id': 32000,
    'pad_to_multiple_of': 64,
    'return_dict': True,
    'output_hidden_states': False,
    'output_attentions': False,
    'torchscript': False,
    'torch_dtype': 'bfloat16',
    'use_bfloat16': False,
    'tf_legacy_loss': False,
    'pruned_heads': {},
    'tie_word_embeddings': True,
    'chunk_size_feed_forward': 0,
    'is_encoder_decoder': False,
    'is_decoder': False,
    'cross_attention_hidden_size': None,
    'add_cross_attention': False,
    'tie_encoder_decoder': False,
    'max_length': 20,
    'min_length': 0,
    'do_sample': False,
    'early_stopping': False,
    'num_beams': 1,
    'num_beam_groups': 1,
    'diversity_penalty': 0.0,
    'temperature': 1.0,
    'top_k': 50,
    'top_p': 1.0,
    'typical_p': 1.0,
    'repetition_penalty': 1.0,
    'length_penalty': 1.0,
    'no_repeat_ngram_size': 0,
    'encoder_no_repeat_ngram_size': 0,
    'bad_words_ids': None,
    'num_return_sequences': 1,
    'output_scores': False,
    'return_dict_in_generate': False,
    'forced_bos_token_id': None,
    'forced_eos_token_id': None,
    'remove_invalid_values': False,
    'exponential_decay_length_penalty': None,
    'suppress_tokens': None,
    'begin_suppress_tokens': None,
    'architectures': ['OpenVLAForActionPrediction'],
    'finetuning_task': None,
    'id2label': {0: 'LABEL_0', 1: 'LABEL_1'},
    'label2id': {'LABEL_0': 0, 'LABEL_1': 1},
    'tokenizer_class': None,
    'prefix': None,
    'bos_token_id': None,
    'eos_token_id': None,
    'sep_token_id': None,
    'decoder_start_token_id': None,
    'task_specific_params': None,
    'problem_type': None,
    '_name_or_path': 'openvla/openvla-7b',
    '_attn_implementation_autoset': True,
    'transformers_version': '4.48.0',
    'auto_map': {
        'AutoConfig': 'openvla/openvla-7b--configuration_prismatic.OpenVLAConfig',
        'AutoModelForVision2Seq': 'openvla/openvla-7b--modeling_prismatic.OpenVLAForActionPrediction',
    },
    'model_type': 'openvla',
}
