name: "GlowTTS"
sample_rate: 22050
n_fft: 1024
n_mels: 80
fmax: 8000
pad_value: -11.52
gin_channels: 0

train_dataset: ???
validation_datasets: ???
test_datasets: null
cmu_dict_path: null

model:

  n_speakers: 1
  gin_channels: ${gin_channels}

  train_ds:
    manifest_filepath: ${train_dataset}
    sample_rate: ${sample_rate}
    batch_size: 32
    max_duration: null
    min_duration: 0.1
    trim: false
    shuffle: True
    num_workers: 8
    cmu_dict_path: ${cmu_dict_path}


  validation_ds:
    manifest_filepath: ${validation_datasets}
    sample_rate: ${sample_rate}
    batch_size: 8
    max_duration: null
    min_duration: 0.1
    trim: false
    shuffle: False
    num_workers: 8
    cmu_dict_path: ${cmu_dict_path}

  test_ds:
    manifest_filepath: ${test_datasets}
    sample_rate: ${sample_rate}
    batch_size: 1
    max_duration: null
    min_duration: 0.1
    trim: false
    shuffle: False
    num_workers: 8
    cmu_dict_path: ${cmu_dict_path}

  parser:
    _target_: nemo.collections.tts.modules.glow_tts_parser.GlowTTSParser
    cmu_dict_path: ${cmu_dict_path}

  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    dither: 0.0
    features: ${n_mels}
    frame_splicing: 1
    highfreq: ${fmax}
    log: true
    log_zero_guard_type: add
    log_zero_guard_value: 1e-05
    lowfreq: 0
    mag_power: 1.0
    n_fft: ${n_fft}
    n_window_size: 1024
    n_window_stride: 256
    normalize: null
    pad_to: 16
    pad_value: ${pad_value}
    preemph: null
    sample_rate: ${sample_rate}
    window: hann
    window_size: null
    window_stride: null

  encoder:
    _target_: nemo.collections.tts.modules.glow_tts.TextEncoder
    n_vocab: 148
    out_channels: ${n_mels}
    hidden_channels: 192
    filter_channels: 768
    filter_channels_dp: 256
    kernel_size: 3
    p_dropout: 0.1
    n_layers: 6
    n_heads: 2
    window_size: 4
    prenet: true
    mean_only: true
    gin_channels: ${gin_channels}

  decoder:
    _target_: nemo.collections.tts.modules.glow_tts.FlowSpecDecoder
    in_channels: ${n_mels}
    hidden_channels: 192
    kernel_size: 5
    n_blocks: 12
    n_layers: 4
    n_sqz: 2
    n_split: 4
    sigmoid_scale: false
    p_dropout: 0.05
    dilation_rate: 1
    gin_channels: ${gin_channels}

  optim:
    name: adam
    lr: 1e-3
    # optimizer arguments
    betas: [0.9, 0.98]
    weight_decay: 0

    # scheduler setup
    sched:
      name: CosineAnnealing

      # Scheduler params
      warmup_steps: 3000
      min_lr: 1e-4
      last_epoch: -1

trainer:
  gpus: -1 # number of gpus
  max_epochs: 350
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  gradient_clip_val: 1.0
  flush_logs_every_n_steps: 1000
  log_every_n_steps: 50
  check_val_every_n_epoch: 5

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: True
  create_checkpoint_callback: True
