name: "SqueezeWave"
sample_rate: 22050
n_fft: 1024
n_mels: 80
fmax: 8000
pad_value: -11.52
train_dataset: ???
validation_datasets: ???

model:
  sigma: 1.0
  train_ds:
    dataset:
      # Use SplicedAudioDataset to use all of training data
      _target_: "nemo.collections.tts.data.datalayers.AudioDataset"
      manifest_filepath: ${train_dataset}
      max_duration: null
      min_duration: 0.1
      n_segments: 16384
      trim: false
    dataloader_params:
      drop_last: true
      pin_memory: true
      shuffle: true
      batch_size: 96
      num_workers: 4

  validation_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.AudioDataset"
      manifest_filepath: ${validation_datasets}
      max_duration: null
      min_duration: 0.1
      n_segments: -1
      trim: false
      # This value is hard-coded to reflect n_window_stride * lcm(2, pad_to)
      truncate_to: 512
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 1
      num_workers: 4

  preprocessor:
    _target_: nemo.collections.asr.parts.preprocessing.features.FilterbankFeatures
    dither: 0.0
    nfilt: ${n_mels}
    frame_splicing: 1
    highfreq: ${fmax}
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1e-05
    lowfreq: 0
    mag_power: 1.0
    n_fft: ${n_fft}

    # SqueezeWave is currently hardcoded to these values for window size and stride
    # Changing these parameters are not recommended
    n_window_size: 1024
    n_window_stride: 256

    normalize: null
    pad_to: 1
    pad_value: ${pad_value}
    preemph: null
    sample_rate: ${sample_rate}
    window: hann
    exact_pad: true

  squeezewave:
    _target_: nemo.collections.tts.modules.squeezewave.SqueezeWaveModule
    n_early_every: 2
    n_early_size: 16
    n_flows: 12
    n_group: 128
    n_mel_channels: ${n_mels}
    n_wn_channels: 256
    n_wn_layers: 8
    wn_kernel_size: 3

  optim:
    name: adam
    lr: 4e-4

trainer:
  gpus: 1 # number of gpus
  max_epochs: 10000
  max_steps: 600000
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: false  # Provided by exp_manager
  logger: false  # Provided by exp_manager
  flush_logs_every_n_steps: 1000
  log_every_n_steps: 200
  check_val_every_n_epoch: 25
  precision: 16

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: true
  create_checkpoint_callback: true
