TASKS = {
    'qasper': {
        'context': 'Article:',
        'response': 'Answer:',
        'query_start': 'Question:',
        'tokens_to_generate': 128,
        'subset': 'Qasper/test.jsonl',
        'chat_instruction': 'Do not provide any explanation.',
    },
    'narrative_qa': {
        'context': 'Story:',
        'response': 'Answer:',
        'tokens_to_generate': 29,
        'subset': 'NarrativeQA/test.jsonl',
        'chat_instruction': 'Do not provide any explanation.',
    },
    'quality': {
        'context': 'Story:',
        'response': 'Answer:',
        'tokens_to_generate': 8,
        'subset': 'QuALITY/validation.jsonl',
        'chat_instruction': 'Do not provide any explanation.',
    },
    'musique': {
        'context': 'Paragraphs:',
        'response': 'Answer:',
        'tokens_to_generate': 24,
        'subset': 'MuSiQue/validation.jsonl',
        'chat_instruction': 'Do not provide any explanation.',
    },
    'space_digest': {
        'context': 'Reviews:',
        'response': 'Percentage of Positive Reviews:',
        'tokens_to_generate': 24,
        'subset': 'SpaceDigest/test.jsonl',
        'chat_instruction': 'Do not provide any explanation.',
    },
    'book_sum_sort': {
        'context': 'Summaries:',
        'response': 'Summary IDs in Correct Order:',
        'tokens_to_generate': 128,
        'subset': 'BookSumSort/validation.jsonl',
        'chat_instruction': 'Do not provide any explanation.',
    },
    'gov_report': {
        'context': 'Report:',
        'response': 'Summary:',
        'tokens_to_generate': 1024,
        'subset': 'GovReport/test.jsonl',
        'chat_instruction': '',
    },
    'gov_report-0': {
        'context': 'Report:',
        'response': 'Summary:',
        'tokens_to_generate': 1024,
        'subset': 'GovReport/test_0.jsonl',
        'chat_instruction': '',
    },
    'gov_report-1': {
        'context': 'Report:',
        'response': 'Summary:',
        'tokens_to_generate': 1024,
        'subset': 'GovReport/test_1.jsonl',
        'chat_instruction': '',
    },
    'gov_report-2': {
        'context': 'Report:',
        'response': 'Summary:',
        'tokens_to_generate': 1024,
        'subset': 'GovReport/test_2.jsonl',
        'chat_instruction': '',
    },
    'gov_report-3': {
        'context': 'Report:',
        'response': 'Summary:',
        'tokens_to_generate': 1024,
        'subset': 'GovReport/test_3.jsonl',
        'chat_instruction': '',
    },
    'gov_report-4': {
        'context': 'Report:',
        'response': 'Summary:',
        'tokens_to_generate': 1024,
        'subset': 'GovReport/test_4.jsonl',
        'chat_instruction': '',
    },
    'summ_screen_fd': {
        'context': 'Episode Script:',
        'response': 'Summary:',
        'tokens_to_generate': 640,
        'subset': 'SummScreenFD/test.jsonl',
        'chat_instruction': '',
    },
    'summ_screen_fd-0': {
        'context': 'Episode Script:',
        'response': 'Summary:',
        'tokens_to_generate': 640,
        'subset': 'SummScreenFD/test_0.jsonl',
        'chat_instruction': '',
    },
    'summ_screen_fd-1': {
        'context': 'Episode Script:',
        'response': 'Summary:',
        'tokens_to_generate': 640,
        'subset': 'SummScreenFD/test_1.jsonl',
        'chat_instruction': '',
    },
    'summ_screen_fd-2': {
        'context': 'Episode Script:',
        'response': 'Summary:',
        'tokens_to_generate': 640,
        'subset': 'SummScreenFD/test_2.jsonl',
        'chat_instruction': '',
    },
    'summ_screen_fd-3': {
        'context': 'Episode Script:',
        'response': 'Summary:',
        'tokens_to_generate': 640,
        'subset': 'SummScreenFD/test_3.jsonl',
        'chat_instruction': '',
    },
    'qmsum': {
        'context': 'Transcript:',
        'response': 'Answer:',
        'tokens_to_generate': 256,
        'subset': 'QMSum/test.jsonl',
        'chat_instruction': '',
    },
    'squality': {
        'context': 'Story:',
        'response': 'Answer:',
        'tokens_to_generate': 640,
        'subset': 'SQuALITY/validation.jsonl',
        'chat_instruction': '',
    },
    "narrativeqa_lb": {
        "context": "Story:",
        "query_start": "Question:",
        "response": "Answer:",
        "tokens_to_generate": 128,
        "subset": "LongBench/narrativeqa.jsonl",
        "chat_instruction": "",
        "template": "You are given a story, which can be either a novel or a movie script, and a question. Answer the question asconcisely as you can, using a single phrase if possible. Do not provide any explanation.\n\nStory: {context}\n\nNow, answer the question based on the story asconcisely as you can, using a single phrase if possible. Do not provide any explanation.\n\nQuestion: {input}\n\nAnswer:"
    },
    "qasper_lb": {
        "context": "Article:",
        "query_start": "Question:",
        "response": "Answer:",
        "tokens_to_generate": 128,
        "subset": "LongBench/qasper.jsonl",
        "chat_instruction": "",
        "template": "You are given a scientific article and a question. Answer the question as concisely as you can, using a single phrase or sentence if possible. If the question cannot be answered based on the information in the article, write 'unanswerable'. If the question is a yes/no question, answer 'yes', 'no', or 'unanswerable'. Do not provide any explanation.\n\nArticle: {context}\n\n Answer the question based on the above article as concisely as you can, using a single phrase or sentence if possible. If the question cannot be answered based on the information in the article, write 'unanswerable'. If the question is a yes/no question, answer 'yes', 'no', or 'unanswerable'. Do not provide any explanation.\n\nQuestion: {input}\n\nAnswer:"
    },
    "multifieldqa_en_lb": {
        "context": "answer briefly.\n\n",
        "query_start": "Question:",
        "response": "Answer:",
        "tokens_to_generate": 64,
        "subset": "LongBench/multifieldqa_en.jsonl",
        "chat_instruction": "",
        "template": "Read the following text and answer briefly.\n\n{context}\n\nNow, answer the following question based on the above text, only give me the answer and do not output any other words.\n\nQuestion: {input}\nAnswer:"
    },
    "multifieldqa_zh_lb": {
        "context": "中文简短回答:",
        "query_start": "\u9898\uff1a",
        "response": "回答:",
        "tokens_to_generate": 64,
        "subset": "LongBench/multifieldqa_zh.jsonl",
        "chat_instruction": "",
        "template": "\u9605\u8bfb\u4ee5\u4e0b\u6587\u5b57\u5e76\u7528\u4e2d\u6587\u7b80\u77ed\u56de\u7b54\uff1a\n\n{context}\n\n\u73b0\u5728\u8bf7\u57fa\u4e8e\u4e0a\u9762\u7684\u6587\u7ae0\u56de\u7b54\u4e0b\u9762\u7684\u95ee\u9898\uff0c\u53ea\u544a\u8bc9\u6211\u7b54\u6848\uff0c\u4e0d\u8981\u8f93\u51fa\u4efb\u4f55\u5176\u4ed6\u5b57\u8bcd\u3002\n\n\u95ee\u9898\uff1a{input}\n\u56de\u7b54\uff1a"
    },
    "hotpotqa_lb": {
        "context": "The following are given passages.\n",
        "query_start": "Question:",
        "response": "Answer:",
        "tokens_to_generate": 32,
        "subset": "LongBench/hotpotqa.jsonl",
        "chat_instruction": "",
        "template": "Answer the question based on the given passages. Only give me the answer and do not output any other words.\n\nThe following are given passages.\n{context}\n\nAnswer the question based on the given passages. Only give me the answer and do not output any other words.\n\nQuestion: {input}\nAnswer:"
    },
    "2wikimqa_lb": {
        "context": "The following are given passages.\n",
        "query_start": "Question:",
        "response": "Answer:",
        "tokens_to_generate": 32,
        "subset": "LongBench/2wikimqa.jsonl",
        "chat_instruction": "",
        "template": "Answer the question based on the given passages. Only give me the answer and do not output any other words.\n\nThe following are given passages.\n{context}\n\nAnswer the question based on the given passages. Only give me the answer and do not output any other words.\n\nQuestion: {input}\nAnswer:"
    },
    "musique_lb": {
        "context": "The following are given passages.\n",
        "query_start": "Question:",
        "response": "Answer:",
        "tokens_to_generate": 32,
        "subset": "LongBench/musique.jsonl",
        "chat_instruction": "",
        "template": "Answer the question based on the given passages. Only give me the answer and do not output any other words.\n\nThe following are given passages.\n{context}\n\nAnswer the question based on the given passages. Only give me the answer and do not output any other words.\n\nQuestion: {input}\nAnswer:"
    },
    "dureader_lb": {
        "context": "文章:",
        "query_start": "\u9898\uff1a",
        "response": "回答",
        "tokens_to_generate": 128,
        "subset": "LongBench/dureader.jsonl",
        "chat_instruction": "",
        "template": "\u8bf7\u57fa\u4e8e\u7ed9\u5b9a\u7684\u6587\u7ae0\u56de\u7b54\u4e0b\u8ff0\u95ee\u9898\u3002\n\n\u6587\u7ae0\uff1a{context}\n\n\u8bf7\u57fa\u4e8e\u4e0a\u8ff0\u6587\u7ae0\u56de\u7b54\u4e0b\u9762\u7684\u95ee\u9898\u3002\n\n\u95ee\u9898\uff1a{input}\n\u56de\u7b54\uff1a"
    },
    "gov_report_lb": {
        "context": "Report:",
        "query_start": "Summary:",
        "response": "Summary:",
        "tokens_to_generate": 512,
        "subset": "LongBench/gov_report.jsonl",
        "chat_instruction": "",
        "template": "You are given a report by a government agency. Write a one-page summary of the report.\n\nReport:\n{context}\n\nNow, write a one-page summary of the report.\n\nSummary:"
    },
    "qmsum_lb": {
        "context": "Transcript:",
        "query_start": "Query:",
        "response": "Answer:",
        "tokens_to_generate": 512,
        "subset": "LongBench/qmsum.jsonl",
        "chat_instruction": "",
        "template": "You are given a meeting transcript and a query containing a question or instruction. Answer the query in one or more sentences.\n\nTranscript:\n{context}\n\nNow, answer the query based on the above meeting transcript in one or more sentences.\n\nQuery: {input}\nAnswer:"
    },
    "multi_news_lb": {
        "context": "News:\n",
        "response": "Summary:",
        "query_start": "Summary:",
        "tokens_to_generate": 512,
        "subset": "LongBench/multi_news.jsonl",
        "chat_instruction": "",
        "template": "You are given several news passages. Write a one-page summary of all news. \n\nNews:\n{context}\n\nNow, write a one-page summary of all the news.\n\nSummary:"
    },
    "vcsum_lb": {
        "context": "会议记录：\n",
        "response": "会议总结:",
        "query_start": "会议总结:",
        "tokens_to_generate": 512,
        "subset": "LongBench/vcsum.jsonl",
        "chat_instruction": "",
        "template": "\u4e0b\u9762\u6709\u4e00\u6bb5\u4f1a\u8bae\u8bb0\u5f55\uff0c\u8bf7\u4f60\u9605\u8bfb\u540e\uff0c\u5199\u4e00\u6bb5\u603b\u7ed3\uff0c\u603b\u7ed3\u4f1a\u8bae\u7684\u5185\u5bb9\u3002\n\u4f1a\u8bae\u8bb0\u5f55\uff1a\n{context}\n\n\u4f1a\u8bae\u603b\u7ed3\uff1a"
    },
    "trec_lb": {
        "context": "Here are some examples of questions.\n\n",
        "response": "Type:",
        "tokens_to_generate": 64,
        "subset": "LongBench/trec.jsonl",
        "chat_instruction": "",
        "template": "Please determine the type of the question below. Here are some examples of questions.\n\n{context}\n{input}"
    },
    "triviaqa_lb": {
        "context": "The following are some examples.\n\n",
        "query_start": "Answer:",
        "response": "Answer:",
        "tokens_to_generate": 32,
        "subset": "LongBench/triviaqa.jsonl",
        "chat_instruction": "",
        "template": "Answer the question based on the given passage. Only give me the answer and do not output any other words. The following are some examples.\n\n{context}\n\n{input}\n"
    },
    "samsum_lb": {
        "context": "The following are some examples.\n\n",
        "query_start": "Summary:",
        "response": "Summary:",
        "tokens_to_generate": 128,
        "subset": "LongBench/samsum.jsonl",
        "chat_instruction": "",
        "template": "Summarize the dialogue into a few short sentences. The following are some examples.\n\n{context}\n\n{input}"
    },
    "lsht_lb": {
        "context": "下面是一些例子。\n\n",
        "query_start": "\n类别:",
        "response": "\n类别:",
        "tokens_to_generate": 64,
        "subset": "LongBench/lsht.jsonl",
        "chat_instruction": "",
        "template": "\u8bf7\u5224\u65ad\u7ed9\u5b9a\u65b0\u95fb\u7684\u7c7b\u522b\uff0c\u4e0b\u9762\u662f\u4e00\u4e9b\u4f8b\u5b50\u3002\n\n{context}\n{input}"
    },
    "passage_count_lb": {
        "context": "how many non-repeating paragraphs are there in total?\n\n",
        "query_start": "",
        "response": "The final answer is:",
        "tokens_to_generate": 32,
        "subset": "LongBench/passage_count.jsonl",
        "chat_instruction": "",
        "template": "There are some paragraphs below sourced from Wikipedia. Some of them may be duplicates. Please carefully read these paragraphs and determine how many unique paragraphs there are after removing duplicates. In other words, how many non-repeating paragraphs are there in total?\n\n{context}\n\nPlease enter the final count of unique paragraphs after removing duplicates. The output format should only contain the number, such as 1, 2, 3, and so on.\n\nThe final answer is:"
    },
    "passage_retrieval_en_lb": {
        "context": "Please determine which paragraph the abstract is from.\n\n",
        "query_start": "The following is an abstract.",
        "response": "The answer is:",
        "tokens_to_generate": 32,
        "subset": "LongBench/passage_retrieval_en.jsonl",
        "chat_instruction": "",
        "template": "Here are 30 paragraphs from Wikipedia, along with an abstract. Please determine which paragraph the abstract is from.\n\n{context}\n\nThe following is an abstract.\n\n{input}\n\nPlease enter the number of the paragraph that the abstract is from. The answer format must be like 'Paragraph 1', 'Paragraph 2', etc.\n\nThe answer is:"
    },
    "passage_retrieval_zh_lb": {
        "context": "请确定给定的摘要出自哪一段。\n\n",
        "query_start":"\u6458\u8981\n\n",
        "response": "答案是:",
        "tokens_to_generate": 32,
        "subset": "LongBench/passage_retrieval_zh.jsonl",
        "chat_instruction": "",
        "template": "\u4ee5\u4e0b\u662f\u82e5\u5e72\u6bb5\u843d\u6587\u5b57\uff0c\u4ee5\u53ca\u5176\u4e2d\u4e00\u4e2a\u6bb5\u843d\u7684\u6458\u8981\u3002\u8bf7\u786e\u5b9a\u7ed9\u5b9a\u7684\u6458\u8981\u51fa\u81ea\u54ea\u4e00\u6bb5\u3002\n\n{context}\n\n\u4e0b\u9762\u662f\u4e00\u4e2a\u6458\u8981\n\n{input}\n\n\u8bf7\u8f93\u5165\u6458\u8981\u6240\u5c5e\u6bb5\u843d\u7684\u7f16\u53f7\u3002\u7b54\u6848\u683c\u5f0f\u5fc5\u987b\u662f'\u6bb5\u843d1'\uff0c'\u6bb5\u843d2'\u7b49\u683c\u5f0f\n\n\u7b54\u6848\u662f\uff1a"
    },
    "lcc_lb": {
        "context": "Please complete the code given below. \n",
        "query_start":"",
        "response": "Next line of code:",
        "tokens_to_generate": 64,
        "subset": "LongBench/lcc.jsonl",
        "chat_instruction": "",
        "template": "Please complete the code given below. \n{context}Next line of code:\n"
    },
    "repobench-p_lb": {
        "context": "Please complete the code given below. \n",
        "query_start":"",
        "response": "Next line of code:",
        "tokens_to_generate": 64,
        "subset": "LongBench/repobench-p.jsonl",
        "chat_instruction": "",
        "template": "Please complete the code given below. \n{context}{input}Next line of code:\n"
    },

}
