HYDRA_FULL_ERROR=1 torchrun --nnode 1 --nproc_per_node 4 megatron_bert_pretraining.py \
    trainer.devices=4 \
    model.data.data_prefix=[1,/workspace/parquet] \
    model.tensor_model_parallel_size=1 \
    model.pipeline_model_parallel_size=2 \
    model.micro_batch_size=4 \
    model.global_batch_size=8 \
    model.data.dataloader_type=LDDL \
    model.tokenizer.vocab_file=/workspace/bert_pile5/bert-large-cased-vocab.txt 