name: &name "ClusterDiarizer"

num_workers: 4
sample_rate: 16000
batch_size: 64

diarizer:
  oracle_num_speakers: ??? # oracle number of speakers or pass null if not known. [int or path to file containing uniq-id with num of speakers of that session]
  max_num_speakers: 20 # max number of speakers for each recording. If oracle num speakers is passed this value is ignored.
  out_dir: ???
  paths2audio_files: ??? #file containing paths to audio files for inference
  path2groundtruth_rttm_files: null #file containing paths to ground truth rttm files for score computation or null if no reference rttms are present

  vad:
    model_path: null #.nemo local model path or pretrained model name or none
    window_length_in_sec: 0.15
    shift_length_in_sec: 0.01
    vad_decision_smoothing: True
    smoothing_params:
      method: "median" 
      overlap: 0.875
    threshold: null # if not null, use this value and ignore the following onset and offset. Warning! it will be removed in release 1.5!
    postprocessing_params: # Tuned parameter for CH109! (with 11 moved multi-speech sessions as dev set) You might need to choose resonable threshold or tune the threshold on your dev set. Check <NeMo_git_root>/scripts/voice_activity_detection/vad_tune_threshold.py
      onset: 0.4
      offset: 0.7
      pad_onset: 0.05
      pad_offset: -0.1
      min_duration_on: 0.2 
      min_duration_off: 0.2 
      filter_speech_first: True 

  speaker_embeddings:
    oracle_vad_manifest: null
    model_path: ??? #.nemo local model path or pretrained model name (speakerverification_speakernet or speakerdiarization_speakernet)
    window_length_in_sec: 1.5 # window length in sec for speaker embedding extraction
    shift_length_in_sec: 0.75 # shift length in sec for speaker embedding extraction
