name: &name "ClusterDiarizer"

num_workers: 4
sample_rate: 16000
batch_size: 64

diarizer:
  oracle_num_speakers: ??? # oracle number of speakers or pass null if not known. [int or path to file containing uniq-id with num of speakers of that session]
  max_num_speakers: 20 # max number of speakers for each recording. If oracle num speakers is passed this value is ignored.
  out_dir: ???
  paths2audio_files: ??? #file containing paths to audio files for inference
  path2groundtruth_rttm_files: null #file containing paths to ground truth rttm files for score computation or null if no reference rttms are present

  vad:
    model_path: null #.nemo local model path or pretrained model name or none
    window_length_in_sec: 0.15
    shift_length_in_sec: 0.01
    threshold: 0.7 # tune threshold on dev set. Check <NeMo_git_root>/scripts/voice_activity_detection/vad_tune_threshold.py
    vad_decision_smoothing: True
    smoothing_params:
      method: "median" 
      overlap: 0.875

  speaker_embeddings:
    oracle_vad_manifest: null
    model_path: ??? #.nemo local model path or pretrained model name (speakerverification_speakernet or speakerdiarization_speakernet)
    window_length_in_sec: 1.5 # window length in sec for speaker embedding extraction
    shift_length_in_sec: 0.75 # shift length in sec for speaker embedding extraction
