run:
  name: eval_${.task_name}_${.model_train_name}
  time_limit: "04:00:00"
  dependency: "singleton"
  model_train_name: mt5_220m
  task_name: "xnli"
  finetuning_results_dir: ${base_results_dir}/${.model_train_name}/${.task_name}
  results_dir: ${base_results_dir}/${.model_train_name}/${.task_name}_eval

trainer:
  gpus: 8
  num_nodes: 1
  accelerator: ddp
  precision: bf16
  logger: False # logger provided by exp_manager
  checkpoint_callback: False
  replace_sampler_ddp: False
  log_every_n_steps: 10


exp_manager:
  explicit_log_dir: ${evaluation.run.results_dir}
  exp_dir: null
  name: megatron_t5_glue_xnli_eval
  create_checkpoint_callback: False

model:
  restore_from_finetuned_path: ${evaluation.run.finetuning_results_dir}/checkpoints/megatron_t5_glue.nemo # Path to a finetuned T5 .nemo file
  tensor_model_parallel_size: 1 # 1 for 220m, 2 for 3b
  gradient_as_bucket_view: True # Allocate gradients in a contiguous bucket to save memory (less fragmentation and buffer memory)
  megatron_amp_O2: False # Enable O2 optimization for megatron amp
  eval_languages: ['fr', 'de', 'en', 'es'] # List of languages to evaluate zero-shot XNLI performance. Full language list: ar,bg,de,el,en,es,fr,hi,ru,sw,th,tr,ur,vi,zh

  data:
    test_ds:
      task_name: 'xnli'
      file_path: ${data_dir}/glue_data/xnli/xnli.test.tsv # Path to the TSV file for XNLI test
      batch_size: 32
      shuffle: False
      num_workers: 8
      pin_memory: True
      max_seq_length: 512
