project_dir: null
name: SelfAlignmentPretrainingForMedicalEntityLinking
trainer:
  gpus: 1
  num_nodes: 1
  max_epochs: 2
  max_steps: null
  accumulate_grad_batches: 1
  precision: 16
  accelerator: ddp
  gradient_clip_val: 0.0
  log_every_n_steps: 1
  val_check_interval: 2
  checkpoint_callback: false
  logger: false
model:
  nemo_path: ???
  max_seq_length: 128
  language_model:
    pretrained_model_name: bert-base-uncased
    config_file: null
    config: null
    lm_checkpoint: null
  tokenizer:
    tokenizer_name: ${model.language_model.pretrained_model_name}
    vocab_file: null
    tokenizer_model: null
    do_lower_case: true
  loss_params: null
  train_ds:
    data_file: ???
    max_seq_length: ${model.max_seq_length}
    batch_size: 8
    shuffle: true
    num_workers: 2
    pin_memory: false
    drop_last: false
  validation_ds:
    data_file: ??? 
    max_seq_length: ${model.max_seq_length}
    batch_size: 8
    shuffle: false
    num_workers: 2
    pin_memory: false
    drop_last: false
  optim:
    name: adam
    lr: 3.0e-05
    weight_decay: 0.0
    sched:
      name: CosineAnnealing
      warmup_steps: null
      warmup_ratio: 0.1
      min_lr: 0.0
      last_epoch: -1
index:
  dims: 768
  nlist: 2
  top_n: 3
  query_num_factor: 20
  index_save_name: ???
  index_batch_size: 10
  index_ds:
    name: tiny_example
    data_file: ???
    max_seq_length: ${model.max_seq_length}
    batch_size: 100
    shuffle: false
    num_workers: 2
    pin_memory: false
    drop_last: false
  idx_to_id: ${project_dir}/idx_to_id.pkl
  id_to_string: ${project_dir}/id_to_string.pkl
  concept_id_save_name: ${project_dir}/tiny_example_concept_ids.pkl
  embedding_save_name: ${project_dir}/tiny_example_concept_embeddings.hdf5
  pca_embeddings_save_name: null
  apply_pca: false
  pca: null
exp_manager:
  exp_dir: .
  name: ${project_dir}/SelfAlignmentPretrainingTinyExample
  create_tensorboard_logger: true
  create_checkpoint_callback: true
hydra:
  run:
    dir: .
  job_logging:
    root:
      handlers: null
