//Copyright (c) 2019-2022, NVIDIA CORPORATION.  All rights reserved.
//
//NVIDIA CORPORATION and its licensors retain all intellectual property
//and proprietary rights in and to this software, related documentation
//and any modifications thereto.  Any use, reproduction, disclosure or
//distribution of this software and related documentation without an express
//license agreement from NVIDIA CORPORATION is strictly prohibited.
//


#ifndef CUFFTDX_DATABASE_LUT_FP32_INC_HPP

#define CUFFTDX_DATABASE_LUT_FP32_INC_HPP

#include "lut_defines.hpp.inc"

#ifdef _MSC_VER
// truncation of twiddle values is intended
#pragma warning(disable : 4305)
#pragma warning(disable : 4838)
#endif



#include "lut_fp32_0.hpp.inc"



#endif
